[build]
target="armv7-unknown-linux-gnueabihf"

# I feel link this isn't quite the right place for this, because the final linker command duplicates
# these flags many times. I think these are getting added for each library that is compiled.
rustflags = ["-L/home/mch/Work/nordichack/nordichack/rust-ui-gtk/sysroot/lib/arm-linux-gnueabihf", "-L/home/mch/Work/nordichack/nordichack/rust-ui-gtk/sysroot/usr/lib/arm-linux-gnueabihf", "-lgmodule-2.0", "-lX11", "-lXi", "-lXfixes", "-latk-bridge-2.0", "-lepoxy", "-lfribidi", "-lpangoft2-1.0", "-lfontconfig", "-lfreetype", "-lXinerama", "-lXrandr", "-lXcursor", "-lXcomposite", "-lXdamage", "-lxkbcommon", "-lwayland-cursor", "-lwayland-egl", "-lwayland-client", "-lXext", "-lthai", "-lpixman-1", "-lpng16", "-lxcb-shm", "-lxcb", "-lxcb-render", "-lXrender", "-lz", "-lmount", "-latspi", "-lgraphite2", "-luuid", "-lbrotlidec", "-ldatrie", "-lXau", "-lXdmcp", "-lblkid", "-lffi", "-lharfbuzz", "-lrt"]

[target.armv7-unknown-linux-gnueabihf]
#linker = "mylinker3"
