#!/bin/bash -ex

export PI="rustpi.local"
#export PI="treadmill.local"

# Copy necessary files from RPi
mkdir -p sysroot/usr/share/pkgconfig/
mkdir -p sysroot/lib/arm-linux-gnueabihf/pkgconfig/
rsync -av ${PI}:/usr/share/pkgconfig/ sysroot/usr/share/pkgconfig/
rsync -av ${PI}:/usr/lib/arm-linux-gnueabihf/pkgconfig/ sysroot/lib/arm-linux-gnueabihf/pkgconfig/

mkdir -p sysroot/usr/lib/arm-linux-gnueabihf/
rsync -av --include-from=files-from.txt --exclude='*' \
      ${PI}:/usr/lib/arm-linux-gnueabihf/ \
      /home/mch/Work/nordichack/nordichack/rust-ui-gtk/sysroot/usr/lib/arm-linux-gnueabihf/

rsync -av --include-from=files-from-lib.txt --exclude='*' \
      ${PI}:/lib/arm-linux-gnueabihf/ \
      /home/mch/Work/nordichack/nordichack/rust-ui-gtk/sysroot/lib/arm-linux-gnueabihf/

# Some extra symlinks are required for some reason
pushd sysroot/usr/lib/arm-linux-gnueabihf/
ln -fs libthai.so.0.3.1 libthai.so
ln -fs libdatrie.so.1.3.5 libdatrie.so
ln -fs libbrotlidec.so.1.0.7 libbrotlidec.so
ln -fs libbsd.so.0.9.1 libbsd.so
ln -fs liblz4.so.1.8.3 liblz4.so
popd

pushd sysroot/lib/arm-linux-gnueabihf/
ln -fs librt-2.28.so librt.so
popd
